name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore -bl
      working-directory: local-news-backend/LocalNewsApi/
    - name: Build
      run: dotnet build --no-restore
      working-directory: local-news-backend/LocalNewsApi/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: local-news-backend/LocalNewsApiTest/
