name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-x

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: LocalNewsApi
    - name: Build
      run: dotnet build --no-restore
      working-directory: LocalNewsApi
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: LocalNewsApiTest
